id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Push to live branch (publish)
      frequencies:
      - weekday:
          day: Monday
          time: 22:0
      - weekday:
          day: Tuesday
          time: 22:0
      - weekday:
          day: Wednesday
          time: 22:0
      - weekday:
          day: Thursday
          time: 22:0
      - weekday:
          day: Friday
          time: 22:0
      filters: []
      actions:
      - createPullRequest:
          head: main
          base: live
          title: Merge main into live
          body: Please don't squash-merge this PR.
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Admin
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            isActivitySender:
              user: github-actions[bot]
              issueAuthor: False
        - not:
            isActivitySender:
              user: github-actions
              issueAuthor: False
        - not:
            isActivitySender:
              user: azure-sdk
              issueAuthor: False
        - not:
            isActivitySender:
              user: dependabot
              issueAuthor: False
      then:
      - addLabel:
          label: community-contribution
      description: Label community PRs
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: dependencies
      - isActivitySender:
          user: dependabot
          issueAuthor: False
      then:
      - addReply:
          reply: '@dependabot squash and merge'
      description: Reply to dependabot PRs with automation command to squash and merge
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          user: azure-sdk
          issueAuthor: False
      then:
      - addLabel:
          label: azure-sdk-shipit
      description: Label PRs from the Azure SDK bot
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: azure-sdk-shipit
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: Auto-merge Azure SDK PRs with green builds
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: azure-sdk-shipit
      then:
      - disableAutoMerge
      description: Auto-merge Azure SDK PRs with green builds
onFailure: 
onSuccess: 
