import "oaidl.idl";
import "ocidl.idl";

[
    object,
    oleautomation,
    uuid(F586D6F4-AF37-441E-80A6-3D33D977882D)
]
interface IServer : IDispatch
{
    HRESULT ComputePi(
        [out, retval] double *ret);
};

// See the matching Guid and TLB version in DllServer.cs
[
    uuid(46F3FEB2-121D-4830-AA22-0CDA9EA90DC3),
    version( 1.0 )
]
library ServerLib
{
    importlib("stdole2.tlb");

    [
        uuid(AF080472-F173-4D9D-8BE7-435776617347)
    ]
    coclass Server
    {
        [default] interface IServer;
    }
}
