#nullable enable

using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace CsvGenerator;

/// <summary>
/// A source generator that reads <c>.csv</c> additional files and produces a
/// strongly-typed C# class for each one.  The first row of the CSV is treated
/// as column headers (property names) and every subsequent row becomes a static
/// instance exposed through a generated <c>All</c> property.
/// </summary>
[Generator]
public class CsvIncrementalGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter additional files to only .csv files.
        IncrementalValuesProvider<AdditionalText> csvFiles =
            context.AdditionalTextsProvider
                   .Where(static file => Path.GetExtension(file.Path)
                                             .Equals(".csv", System.StringComparison.OrdinalIgnoreCase));

        // Read file content and pair with file name.
        IncrementalValuesProvider<(string ClassName, string Text)?> csvData =
            csvFiles.Select(static (file, ct) =>
            {
                string? text = file.GetText(ct)?.ToString();
                if (text is null)
                    return null;

                string className = Path.GetFileNameWithoutExtension(file.Path);
                return ((string ClassName, string Text)?)(className, text);
            });

        // Generate source for each CSV file.
        context.RegisterSourceOutput(csvData, static (spc, csv) =>
        {
            if (csv is null)
                return;

            string? source = GenerateClassFromCsv(csv.Value.ClassName, csv.Value.Text);
            if (source is not null)
            {
                spc.AddSource($"{csv.Value.ClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
            }
        });
    }

    private static string? GenerateClassFromCsv(string className, string csvText)
    {
        string[] lines = csvText.Split(new[] { "\r\n", "\n" }, System.StringSplitOptions.RemoveEmptyEntries);
        if (lines.Length < 2) // Need at least a header and one data row.
            return null;

        string[] headers = ParseCsvLine(lines[0]);
        if (headers.Length == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine();
        sb.AppendLine("namespace CsvGenerated");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Strongly-typed class generated from {className}.csv.</summary>");
        sb.AppendLine($"    public sealed class {className}");
        sb.AppendLine("    {");

        // Properties (all strings for simplicity)
        foreach (string header in headers)
        {
            sb.AppendLine($"        public string {SanitizeIdentifier(header)} {{ get; }}");
        }

        sb.AppendLine();

        // Constructor
        sb.Append($"        private {className}(");
        sb.Append(string.Join(", ", headers.Select(h => $"string {CamelCase(SanitizeIdentifier(h))}")));
        sb.AppendLine(")");
        sb.AppendLine("        {");
        foreach (string header in headers)
        {
            string prop = SanitizeIdentifier(header);
            sb.AppendLine($"            {prop} = {CamelCase(prop)};");
        }
        sb.AppendLine("        }");
        sb.AppendLine();

        // All property – static list of rows
        sb.AppendLine("        /// <summary>All rows from the CSV data.</summary>");
        sb.AppendLine($"        public static global::System.Collections.Generic.IReadOnlyList<{className}> All {{ get; }} =");
        sb.AppendLine($"            new {className}[]");
        sb.AppendLine("            {");

        for (int i = 1; i < lines.Length; i++)
        {
            string[] values = ParseCsvLine(lines[i]);
            // Pad or trim to match header count.
            string[] row = new string[headers.Length];
            for (int j = 0; j < headers.Length; j++)
            {
                row[j] = j < values.Length ? values[j] : string.Empty;
            }

            sb.Append($"                new {className}(");
            sb.Append(string.Join(", ", row.Select(EscapeString)));
            sb.AppendLine("),");
        }

        sb.AppendLine("            };");

        // ToString override
        sb.AppendLine();
        sb.AppendLine("        public override string ToString() =>");
        sb.Append("            $\"");
        sb.Append(string.Join(", ", headers.Select(h =>
        {
            string prop = SanitizeIdentifier(h);
            return $"{prop}={{{prop}}}";
        })));
        sb.AppendLine("\";");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string[] ParseCsvLine(string line)
    {
        // Simple CSV parser – handles quoted fields but not escaped quotes inside quotes.
        var fields = new System.Collections.Generic.List<string>();
        var current = new StringBuilder();
        bool inQuotes = false;

        for (int i = 0; i < line.Length; i++)
        {
            char c = line[i];
            if (c == '"')
            {
                inQuotes = !inQuotes;
            }
            else if (c == ',' && !inQuotes)
            {
                fields.Add(current.ToString().Trim());
                current.Clear();
            }
            else
            {
                current.Append(c);
            }
        }
        fields.Add(current.ToString().Trim());
        return fields.ToArray();
    }

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder();
        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
        }

        string result = sb.ToString();
        if (result.Length == 0)
            return "_";

        // Ensure starts with letter or underscore.
        if (char.IsDigit(result[0]))
            result = "_" + result;

        // PascalCase first letter.
        return char.ToUpperInvariant(result[0]) + result.Substring(1);
    }

    private static string CamelCase(string name)
    {
        if (name.Length == 0)
            return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeString(string value) =>
        $"\"{value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
}
