//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBrowseBooks")]
public interface IBrowseBooks
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBrowseBooks/BrowseBooks", ReplyAction="http://tempuri.org/IBrowseBooks/BrowseBooksResponse")]
    string[] BrowseBooks();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBrowseBooksChannel : IBrowseBooks, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BrowseBooksClient : System.ServiceModel.ClientBase<IBrowseBooks>, IBrowseBooks
{
    
    public BrowseBooksClient()
    {
    }
    
    public BrowseBooksClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BrowseBooksClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BrowseBooksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BrowseBooksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] BrowseBooks()
    {
        return base.Channel.BrowseBooks();
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IBuyBook")]
public interface IBuyBook
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuyBook/BuyBook", ReplyAction="http://tempuri.org/IBuyBook/BuyBookResponse")]
    string BuyBook(string emailAddress, string shipAddress);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IBuyBookChannel : IBuyBook, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class BuyBookClient : System.ServiceModel.ClientBase<IBuyBook>, IBuyBook
{
    
    public BuyBookClient()
    {
    }
    
    public BuyBookClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public BuyBookClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BuyBookClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public BuyBookClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string BuyBook(string emailAddress, string shipAddress)
    {
        return base.Channel.BuyBook(emailAddress, shipAddress);
    }
}
