//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.109
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://stockservice.contoso.com/wse/samples/2003/06", ClrNamespace="stockservice.contoso.com.wse.samples._2003._06")]

namespace stockservice.contoso.com.wse.samples._2003._06
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StockQuoteRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private stockservice.contoso.com.wse.samples._2003._06.ArrayOfString symbolsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public stockservice.contoso.com.wse.samples._2003._06.ArrayOfString symbols
        {
            get
            {
                return this.symbolsField;
            }
            set
            {
                this.symbolsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(ItemName="Symbol")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(ItemName = "StockQuote", Namespace = "http://tempuri.org/")]
    public class StockQuotes : System.Collections.Generic.List<stockservice.contoso.com.wse.samples._2003._06.StockQuote>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StockQuote : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SymbolField;
        
        private double LastField;
        
        private System.DateTime DateField;
        
        private double ChangeField;
        
        private double OpenField;
        
        private double HighField;
        
        private double LowField;
        
        private long VolumeField;
        
        private long MarketCapField;
        
        private double PreviousCloseField;
        
        private double PreviousChangeField;
        
        private double Low52WeekField;
        
        private double High52WeekField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Last
        {
            get
            {
                return this.LastField;
            }
            set
            {
                this.LastField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Change
        {
            get
            {
                return this.ChangeField;
            }
            set
            {
                this.ChangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double Open
        {
            get
            {
                return this.OpenField;
            }
            set
            {
                this.OpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double High
        {
            get
            {
                return this.HighField;
            }
            set
            {
                this.HighField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Low
        {
            get
            {
                return this.LowField;
            }
            set
            {
                this.LowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long MarketCap
        {
            get
            {
                return this.MarketCapField;
            }
            set
            {
                this.MarketCapField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double PreviousClose
        {
            get
            {
                return this.PreviousCloseField;
            }
            set
            {
                this.PreviousCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double PreviousChange
        {
            get
            {
                return this.PreviousChangeField;
            }
            set
            {
                this.PreviousChangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double Low52Week
        {
            get
            {
                return this.Low52WeekField;
            }
            set
            {
                this.Low52WeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double High52Week
        {
            get
            {
                return this.High52WeekField;
            }
            set
            {
                this.High52WeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://stockservice.contoso.com/wse/samples/2003/06", ConfigurationName="StockServicePortType")]
public interface StockServicePortType
{
    
    // CODEGEN: Generating message contract since the operation GetStockQuotes is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="http://stockservice.contoso.com/wse/samples/2003/06/StockQuoteRequest", ReplyAction="*")]
    GetStockQuotesResponse GetStockQuotes(GetStockQuotesRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStockQuotesRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://stockservice.contoso.com/wse/samples/2003/06", Order=0)]
    public stockservice.contoso.com.wse.samples._2003._06.StockQuoteRequest StockQuoteRequest;
    
    public GetStockQuotesRequest()
    {
    }
    
    public GetStockQuotesRequest(stockservice.contoso.com.wse.samples._2003._06.StockQuoteRequest StockQuoteRequest)
    {
        this.StockQuoteRequest = StockQuoteRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetStockQuotesResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public stockservice.contoso.com.wse.samples._2003._06.StockQuotes StockQuotes;
    
    public GetStockQuotesResponse()
    {
    }
    
    public GetStockQuotesResponse(stockservice.contoso.com.wse.samples._2003._06.StockQuotes StockQuotes)
    {
        this.StockQuotes = StockQuotes;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface StockServicePortTypeChannel : StockServicePortType, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StockServicePortTypeClient : System.ServiceModel.ClientBase<StockServicePortType>, StockServicePortType
{
    
    public StockServicePortTypeClient()
    {
    }
    
    public StockServicePortTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StockServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StockServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StockServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    GetStockQuotesResponse StockServicePortType.GetStockQuotes(GetStockQuotesRequest request)
    {
        return base.Channel.GetStockQuotes(request);
    }
    
    public stockservice.contoso.com.wse.samples._2003._06.StockQuotes GetStockQuotes(stockservice.contoso.com.wse.samples._2003._06.StockQuoteRequest StockQuoteRequest)
    {
        GetStockQuotesRequest inValue = new GetStockQuotesRequest();
        inValue.StockQuoteRequest = StockQuoteRequest;
        GetStockQuotesResponse retVal = ((StockServicePortType)(this)).GetStockQuotes(inValue);
        return retVal.StockQuotes;
    }
}
