//----------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All rights reserved.
//----------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://Microsoft.Samples.MSMQTwoWay", ClrNamespace="Microsoft.Samples.MSMQTwoWay")]
namespace Microsoft.Samples.MSMQTwoWay
{     
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.Samples.MSMQTwoWay", ConfigurationName="Microsoft.Samples.MSMQTwoWay.IOrderStatus")]
    public interface IOrderStatus
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.Samples.MSMQTwoWay/IOrderStatus/OrderStatus")]
        void OrderStatus(string poNumber, string status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderStatusChannel : Microsoft.Samples.MSMQTwoWay.IOrderStatus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderStatusClient : System.ServiceModel.ClientBase<Microsoft.Samples.MSMQTwoWay.IOrderStatus>, Microsoft.Samples.MSMQTwoWay.IOrderStatus
    {
        
        public OrderStatusClient()
        {
        }
        
        public OrderStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public OrderStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public OrderStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void OrderStatus(string poNumber, string status)
        {
            base.Channel.OrderStatus(poNumber, status);
        }
    }    
}
