using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Xunit;
using System.Text;

namespace CsvGenerator.Test;

public class CsvGeneratorTests
{
    [Fact]
    public async Task CsvWithHeadersAndRows_GeneratesClass()
    {
        string csvContent = "Name,Country\nTokyo,Japan\nDelhi,India\n";

        string expectedGenerated = @"// <auto-generated />

namespace CsvGenerated
{
    /// <summary>Strongly-typed class generated from Cities.csv.</summary>
    public sealed class Cities
    {
        public string Name { get; }
        public string Country { get; }

        private Cities(string name, string country)
        {
            Name = name;
            Country = country;
        }

        /// <summary>All rows from the CSV data.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<Cities> All { get; } =
            new Cities[]
            {
                new Cities(""Tokyo"", ""Japan""),
                new Cities(""Delhi"", ""India""),
            };

        public override string ToString() =>
            $""Name={Name}, Country={Country}"";
    }
}
";

        var test = new CSharpSourceGeneratorTest<CsvIncrementalGenerator, DefaultVerifier>
        {
            TestCode = "// Intentionally empty, CSV generator does not need C# input.",
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.AdditionalFiles.Add(("Data/Cities.csv", csvContent));

        test.TestState.GeneratedSources.Add(
            (typeof(CsvIncrementalGenerator), "Cities.g.cs", expectedGenerated));

        await test.RunAsync();
    }

    [Fact]
    public async Task CsvWithHeaderOnly_NoOutput()
    {
        // Only a header row, no data rows – generator should not produce output.
        string csvContent = "Name,Country\n";

        var test = new CSharpSourceGeneratorTest<CsvIncrementalGenerator, DefaultVerifier>
        {
            TestCode = "// Intentionally empty.",
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.AdditionalFiles.Add(("Data/Cities.csv", csvContent));

        // No generated sources expected.
        await test.RunAsync();
    }

    [Fact]
    public async Task NonCsvAdditionalFile_IsIgnored()
    {
        var test = new CSharpSourceGeneratorTest<CsvIncrementalGenerator, DefaultVerifier>
        {
            TestCode = "// Intentionally empty.",
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.AdditionalFiles.Add(("Data/readme.txt", "This is not a CSV file."));

        // No generated sources expected.
        await test.RunAsync();
    }

    [Fact]
    public async Task CsvWithThreeColumns_GeneratesAllProperties()
    {
        string csvContent = "Id,Name,Score\n1,Alice,95\n2,Bob,87\n";

        string expectedGenerated = @"// <auto-generated />

namespace CsvGenerated
{
    /// <summary>Strongly-typed class generated from Students.csv.</summary>
    public sealed class Students
    {
        public string Id { get; }
        public string Name { get; }
        public string Score { get; }

        private Students(string id, string name, string score)
        {
            Id = id;
            Name = name;
            Score = score;
        }

        /// <summary>All rows from the CSV data.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<Students> All { get; } =
            new Students[]
            {
                new Students(""1"", ""Alice"", ""95""),
                new Students(""2"", ""Bob"", ""87""),
            };

        public override string ToString() =>
            $""Id={Id}, Name={Name}, Score={Score}"";
    }
}
";

        var test = new CSharpSourceGeneratorTest<CsvIncrementalGenerator, DefaultVerifier>
        {
            TestCode = "// Intentionally empty.",
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.AdditionalFiles.Add(("Data/Students.csv", csvContent));

        test.TestState.GeneratedSources.Add(
            (typeof(CsvIncrementalGenerator), "Students.g.cs", expectedGenerated));

        await test.RunAsync();
    }
}
