//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.Samples.Mtom", ConfigurationName="IUpload")]
public interface IUpload
{
    [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.Mtom/IUpload/Upload", ReplyAction="http://Microsoft.Samples.Mtom/IUpload/UploadResponse")]
    int Upload(System.IO.Stream data);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUploadChannel : IUpload, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UploadClient : System.ServiceModel.ClientBase<IUpload>, IUpload
{
    
    public UploadClient()
    {
    }
    
    public UploadClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UploadClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UploadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UploadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int Upload(System.IO.Stream data)
    {
        return base.Channel.Upload(data);
    }
}
