' Copyright (c) Microsoft Corporation.  All Rights Reserved.
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



Namespace Microsoft.ServiceModel.Samples

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://Microsoft.ServiceModel.Samples", ConfigurationName:="Microsoft.ServiceModel.Samples.ISampleContract", CallbackContract:=GetType(Microsoft.ServiceModel.Samples.ISampleContractCallback), SessionMode:=System.ServiceModel.SessionMode.Required)> _
    Public Interface ISampleContract

        <System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ISampleContract/Subscribe", ReplyAction:="http://Microsoft.ServiceModel.Samples/ISampleContract/SubscribeResponse")> _
        Sub Subscribe()

        <System.ServiceModel.OperationContractAttribute(IsTerminating:=True, Action:="http://Microsoft.ServiceModel.Samples/ISampleContract/Unsubscribe", ReplyAction:="http://Microsoft.ServiceModel.Samples/ISampleContract/UnsubscribeResponse")> _
        Sub Unsubscribe()

        <System.ServiceModel.OperationContractAttribute(IsOneWay:=True, Action:="http://Microsoft.ServiceModel.Samples/ISampleContract/PublishPriceChange")> _
        Sub PublishPriceChange(ByVal item As String, ByVal price As Double, ByVal change As Double)
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface ISampleContractCallback

        <System.ServiceModel.OperationContractAttribute(IsOneWay:=True, Action:="http://Microsoft.ServiceModel.Samples/ISampleContract/PriceChange")> _
        Sub PriceChange(ByVal item As String, ByVal price As Double, ByVal change As Double)
    End Interface

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface ISampleContractChannel
        Inherits Microsoft.ServiceModel.Samples.ISampleContract, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Partial Public Class SampleContractClient
        Inherits System.ServiceModel.DuplexClientBase(Of Microsoft.ServiceModel.Samples.ISampleContract)
        Implements Microsoft.ServiceModel.Samples.ISampleContract

        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub

        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub

        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub

        Public Sub Subscribe() Implements Microsoft.ServiceModel.Samples.ISampleContract.Subscribe
            MyBase.Channel.Subscribe()
        End Sub

        Public Sub Unsubscribe() Implements Microsoft.ServiceModel.Samples.ISampleContract.Unsubscribe
            MyBase.Channel.Unsubscribe()
        End Sub

        Public Sub PublishPriceChange(ByVal item As String, ByVal price As Double, ByVal change As Double) Implements Microsoft.ServiceModel.Samples.ISampleContract.PublishPriceChange
            MyBase.Channel.PublishPriceChange(item, price, change)
        End Sub
    End Class
End Namespace
