//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21019.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexNumber", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Samples.POCO")]
    [System.SerializableAttribute()]
    public partial class ComplexNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImaginaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RealField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Imaginary {
            get {
                return this.ImaginaryField;
            }
            set {
                if ((this.ImaginaryField.Equals(value) != true)) {
                    this.ImaginaryField = value;
                    this.RaisePropertyChanged("Imaginary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Real {
            get {
                return this.RealField;
            }
            set {
                if ((this.RealField.Equals(value) != true)) {
                    this.RealField = value;
                    this.RaisePropertyChanged("Real");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.Samples.POCO", ConfigurationName="ServiceReference.IDataContractCalculator")]
    public interface IDataContractCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.POCO/IDataContractCalculator/Add", ReplyAction="http://Microsoft.Samples.POCO/IDataContractCalculator/AddResponse")]
        Client.ServiceReference.ComplexNumber Add(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.POCO/IDataContractCalculator/Subtract", ReplyAction="http://Microsoft.Samples.POCO/IDataContractCalculator/SubtractResponse")]
        Client.ServiceReference.ComplexNumber Subtract(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.POCO/IDataContractCalculator/Multiply", ReplyAction="http://Microsoft.Samples.POCO/IDataContractCalculator/MultiplyResponse")]
        Client.ServiceReference.ComplexNumber Multiply(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.Samples.POCO/IDataContractCalculator/Divide", ReplyAction="http://Microsoft.Samples.POCO/IDataContractCalculator/DivideResponse")]
        Client.ServiceReference.ComplexNumber Divide(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataContractCalculatorChannel : Client.ServiceReference.IDataContractCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataContractCalculatorClient : System.ServiceModel.ClientBase<Client.ServiceReference.IDataContractCalculator>, Client.ServiceReference.IDataContractCalculator {
        
        public DataContractCalculatorClient() {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContractCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataContractCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.ServiceReference.ComplexNumber Add(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public Client.ServiceReference.ComplexNumber Subtract(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2) {
            return base.Channel.Subtract(n1, n2);
        }
        
        public Client.ServiceReference.ComplexNumber Multiply(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2) {
            return base.Channel.Multiply(n1, n2);
        }
        
        public Client.ServiceReference.ComplexNumber Divide(Client.ServiceReference.ComplexNumber n1, Client.ServiceReference.ComplexNumber n2) {
            return base.Channel.Divide(n1, n2);
        }
    }
}
