'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IBrowseBooks")> _
Public Interface IBrowseBooks

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBrowseBooks/BrowseBooks", ReplyAction:="http://tempuri.org/IBrowseBooks/BrowseBooksResponse")> _
    Function BrowseBooks() As String()
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface IBrowseBooksChannel
    Inherits IBrowseBooks, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class BrowseBooksClient
    Inherits System.ServiceModel.ClientBase(Of IBrowseBooks)
    Implements IBrowseBooks

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Public Function BrowseBooks() As String() Implements IBrowseBooks.BrowseBooks
        Return MyBase.Channel.BrowseBooks
    End Function
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IBuyBook")> _
Public Interface IBuyBook

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBuyBook/BuyBook", ReplyAction:="http://tempuri.org/IBuyBook/BuyBookResponse")> _
    Function BuyBook(ByVal emailAddress As String, ByVal shipAddress As String) As String
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Public Interface IBuyBookChannel
    Inherits IBuyBook, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
Partial Public Class BuyBookClient
    Inherits System.ServiceModel.ClientBase(Of IBuyBook)
    Implements IBuyBook

    Public Sub New()
        MyBase.New()
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Public Function BuyBook(ByVal emailAddress As String, ByVal shipAddress As String) As String Implements IBuyBook.BuyBook
        Return MyBase.Channel.BuyBook(emailAddress, shipAddress)
    End Function
End Class
