//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formatter {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Formatter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Date and Time.
        /// </summary>
        internal static string DateBoxText {
            get {
                return ResourceManager.GetString("DateBoxText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Format String:.
        /// </summary>
        internal static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;Invariant&gt;.
        /// </summary>
        internal static string InvariantCultureName {
            get {
                return ResourceManager.GetString("InvariantCultureName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value to format is not a valid date and time..
        /// </summary>
        internal static string MSG_InvalidDate {
            get {
                return ResourceManager.GetString("MSG_InvalidDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value to format is not a valid date and time with an offset..
        /// </summary>
        internal static string MSG_InvalidDTO {
            get {
                return ResourceManager.GetString("MSG_InvalidDTO", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value to format is not a valid floating point number..
        /// </summary>
        internal static string MSG_InvalidFloat {
            get {
                return ResourceManager.GetString("MSG_InvalidFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The format string is invalid..
        /// </summary>
        internal static string MSG_InvalidFormat {
            get {
                return ResourceManager.GetString("MSG_InvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value to format is not a valid integer number..
        /// </summary>
        internal static string MSG_InvalidInteger {
            get {
                return ResourceManager.GetString("MSG_InvalidInteger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Number.
        /// </summary>
        internal static string NumberBoxText {
            get {
                return ResourceManager.GetString("NumberBoxText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Display.
        /// </summary>
        internal static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Result String:.
        /// </summary>
        internal static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &amp;Value:.
        /// </summary>
        internal static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Formatting Utility.
        /// </summary>
        internal static string WindowCaption {
            get {
                return ResourceManager.GetString("WindowCaption", resourceCulture);
            }
        }
    }
}
