using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace GenerateMembers.Test;

[TestClass]
public class GenerateMembersGeneratorTests
{
    [TestMethod]
    public async Task ClassWithProperties_GeneratesDescribeAndPropertyNames()
    {
        string source = @"
using GenerateMembersGenerator;

namespace TestNamespace
{
    [GenerateMembers]
    public partial class Person
    {
        public string FirstName { get; set; }
        public int Age { get; set; }
    }
}
";

        string expectedGenerated = @"// <auto-generated />
namespace TestNamespace
{
    partial class Person
    {
        /// <summary>Gets the names of all instance properties.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<string> PropertyNames { get; } =
            new string[] { ""FirstName"", ""Age"" };

        /// <summary>Returns a human-readable description of this instance.</summary>
        public string Describe()
        {
            var sb = new global::System.Text.StringBuilder();
            sb.AppendLine(""Person"");
            sb.AppendLine($""  FirstName = {FirstName}"");
            sb.AppendLine($""  Age = {Age}"");
            return sb.ToString();
        }
    }
}
";

        var test = new CSharpSourceGeneratorTest<GenerateMembersGenerator.GenerateMembersIncrementalGenerator, DefaultVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "GenerateMembersAttribute.g.cs",
             GenerateMembersAttributeSource));

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "TestNamespace.Person.GeneratedMembers.g.cs",
             expectedGenerated));

        await test.RunAsync();
    }

    [TestMethod]
    public async Task StructWithAttribute_GeneratesCorrectly()
    {
        string source = @"
using GenerateMembersGenerator;

namespace TestNamespace
{
    [GenerateMembers]
    public partial struct Point
    {
        public int X { get; set; }
        public int Y { get; set; }
    }
}
";

        string expectedGenerated = @"// <auto-generated />
namespace TestNamespace
{
    partial struct Point
    {
        /// <summary>Gets the names of all instance properties.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<string> PropertyNames { get; } =
            new string[] { ""X"", ""Y"" };

        /// <summary>Returns a human-readable description of this instance.</summary>
        public string Describe()
        {
            var sb = new global::System.Text.StringBuilder();
            sb.AppendLine(""Point"");
            sb.AppendLine($""  X = {X}"");
            sb.AppendLine($""  Y = {Y}"");
            return sb.ToString();
        }
    }
}
";

        var test = new CSharpSourceGeneratorTest<GenerateMembersGenerator.GenerateMembersIncrementalGenerator, DefaultVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "GenerateMembersAttribute.g.cs",
             GenerateMembersAttributeSource));

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "TestNamespace.Point.GeneratedMembers.g.cs",
             expectedGenerated));

        await test.RunAsync();
    }

    [TestMethod]
    public async Task ClassWithoutAttribute_NoGeneratedMembers()
    {
        string source = @"
public class Person
{
    public string FirstName { get; set; }
    public int Age { get; set; }
}
";

        var test = new CSharpSourceGeneratorTest<GenerateMembersGenerator.GenerateMembersIncrementalGenerator, DefaultVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        // Only the attribute source should be generated, no member generation.
        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "GenerateMembersAttribute.g.cs",
             GenerateMembersAttributeSource));

        await test.RunAsync();
    }

    [TestMethod]
    public async Task ClassInGlobalNamespace_GeneratesWithoutNamespaceBlock()
    {
        string source = @"
using GenerateMembersGenerator;

[GenerateMembers]
public partial class Item
{
    public string Name { get; set; }
}
";

        string expectedGenerated = @"// <auto-generated />
    partial class Item
    {
        /// <summary>Gets the names of all instance properties.</summary>
        public static global::System.Collections.Generic.IReadOnlyList<string> PropertyNames { get; } =
            new string[] { ""Name"" };

        /// <summary>Returns a human-readable description of this instance.</summary>
        public string Describe()
        {
            var sb = new global::System.Text.StringBuilder();
            sb.AppendLine(""Item"");
            sb.AppendLine($""  Name = {Name}"");
            return sb.ToString();
        }
    }
";

        var test = new CSharpSourceGeneratorTest<GenerateMembersGenerator.GenerateMembersIncrementalGenerator, DefaultVerifier>
        {
            TestCode = source,
            ReferenceAssemblies = ReferenceAssemblies.Net.Net80,
        };

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "GenerateMembersAttribute.g.cs",
             GenerateMembersAttributeSource));

        test.TestState.GeneratedSources.Add(
            (typeof(GenerateMembersGenerator.GenerateMembersIncrementalGenerator),
             "Item.GeneratedMembers.g.cs",
             expectedGenerated));

        await test.RunAsync();
    }

    private const string GenerateMembersAttributeSource = @"// <auto-generated />
namespace GenerateMembersGenerator
{
    /// <summary>
    /// Add this attribute to a partial class or struct to automatically generate
    /// a <c>Describe()</c> method and a <c>PropertyNames</c> list.
    /// </summary>
    [global::System.AttributeUsage(global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct)]
    internal sealed class GenerateMembersAttribute : global::System.Attribute
    {
    }
}
";
}
