//  Copyright (c) Microsoft Corporation. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ICalculatorContract")]
public interface ICalculatorContract
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ICalculatorContract/Add", ReplyAction = "http://tempuri.org/ICalculatorContract/AddResponse")]
    int Add(int x, int y, System.Guid clientTransactionId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICalculatorContractChannel : ICalculatorContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CalculatorContractClient : System.ServiceModel.ClientBase<ICalculatorContract>, ICalculatorContract
{

    public CalculatorContractClient()
    {
    }

    public CalculatorContractClient(string endpointConfigurationName)
        :
            base(endpointConfigurationName)
    {
    }

    public CalculatorContractClient(string endpointConfigurationName, string remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CalculatorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public CalculatorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(binding, remoteAddress)
    {
    }

    public int Add(int x, int y, System.Guid clientTransactionId)
    {
        return base.Channel.Add(x, y, clientTransactionId);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDatagramContract")]
public interface IDatagramContract
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IDatagramContract/Hello")]
    void Hello();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDatagramContractChannel : IDatagramContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DatagramContractClient : System.ServiceModel.ClientBase<IDatagramContract>, IDatagramContract
{

    public DatagramContractClient()
    {
    }

    public DatagramContractClient(string endpointConfigurationName)
        :
            base(endpointConfigurationName)
    {
    }

    public DatagramContractClient(string endpointConfigurationName, string remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DatagramContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public DatagramContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress)
        :
            base(binding, remoteAddress)
    {
    }

    public void Hello()
    {
        base.Channel.Hello();
    }
}
