//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21019.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiringRequestService.Contoso.InboxService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboxItem", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Samples.Inbox")]
    [System.SerializableAttribute()]
    public partial class InboxItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InboxEntryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InboxEntryDate {
            get {
                return this.InboxEntryDateField;
            }
            set {
                if ((this.InboxEntryDateField.Equals(value) != true)) {
                    this.InboxEntryDateField = value;
                    this.RaisePropertyChanged("InboxEntryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartedBy {
            get {
                return this.StartedByField;
            }
            set {
                if ((object.ReferenceEquals(this.StartedByField, value) != true)) {
                    this.StartedByField = value;
                    this.RaisePropertyChanged("StartedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Contoso.InboxService.IInboxService")]
    public interface IInboxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/Add", ReplyAction="http://tempuri.org/IInboxService/AddResponse")]
        HiringRequestService.Contoso.InboxService.AddResponse Add(HiringRequestService.Contoso.InboxService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/Remove", ReplyAction="http://tempuri.org/IInboxService/RemoveResponse")]
        HiringRequestService.Contoso.InboxService.RemoveResponse Remove(HiringRequestService.Contoso.InboxService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/GetRequestsFor", ReplyAction="http://tempuri.org/IInboxService/GetRequestsForResponse")]
        HiringRequestService.Contoso.InboxService.GetRequestsForResponse GetRequestsFor(HiringRequestService.Contoso.InboxService.GetRequestsForRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/GetRequestsStartedBy", ReplyAction="http://tempuri.org/IInboxService/GetRequestsStartedByResponse")]
        HiringRequestService.Contoso.InboxService.GetRequestsStartedByResponse GetRequestsStartedBy(HiringRequestService.Contoso.InboxService.GetRequestsStartedByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/GetArchivedRequestsStartedBy", ReplyAction="http://tempuri.org/IInboxService/GetArchivedRequestsStartedByResponse")]
        HiringRequestService.Contoso.InboxService.GetArchivedRequestsStartedByResponse GetArchivedRequestsStartedBy(HiringRequestService.Contoso.InboxService.GetArchivedRequestsStartedByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboxService/Archive", ReplyAction="http://tempuri.org/IInboxService/ArchiveResponse")]
        HiringRequestService.Contoso.InboxService.ArchiveResponse Archive(HiringRequestService.Contoso.InboxService.ArchiveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string requestCreatorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string userId;
        
        public AddRequest() {
        }
        
        public AddRequest(string requestId, string title, string state, string requestCreatorId, string userId) {
            this.requestId = requestId;
            this.title = title;
            this.state = state;
            this.requestCreatorId = requestCreatorId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddResponse {
        
        public AddResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Remove", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userId;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(string requestId, string userId) {
            this.requestId = requestId;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RemoveResponse {
        
        public RemoveResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestsFor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestsForRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetRequestsForRequest() {
        }
        
        public GetRequestsForRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestsForResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestsForResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HiringRequestService.Contoso.InboxService.InboxItem[] GetRequestsForResult;
        
        public GetRequestsForResponse() {
        }
        
        public GetRequestsForResponse(HiringRequestService.Contoso.InboxService.InboxItem[] GetRequestsForResult) {
            this.GetRequestsForResult = GetRequestsForResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestsStartedBy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestsStartedByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetRequestsStartedByRequest() {
        }
        
        public GetRequestsStartedByRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRequestsStartedByResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequestsStartedByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HiringRequestService.Contoso.InboxService.InboxItem[] GetRequestsStartedByResult;
        
        public GetRequestsStartedByResponse() {
        }
        
        public GetRequestsStartedByResponse(HiringRequestService.Contoso.InboxService.InboxItem[] GetRequestsStartedByResult) {
            this.GetRequestsStartedByResult = GetRequestsStartedByResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArchivedRequestsStartedBy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArchivedRequestsStartedByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string userId;
        
        public GetArchivedRequestsStartedByRequest() {
        }
        
        public GetArchivedRequestsStartedByRequest(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArchivedRequestsStartedByResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetArchivedRequestsStartedByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public HiringRequestService.Contoso.InboxService.InboxItem[] GetArchivedRequestsStartedByResult;
        
        public GetArchivedRequestsStartedByResponse() {
        }
        
        public GetArchivedRequestsStartedByResponse(HiringRequestService.Contoso.InboxService.InboxItem[] GetArchivedRequestsStartedByResult) {
            this.GetArchivedRequestsStartedByResult = GetArchivedRequestsStartedByResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Archive", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArchiveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string requestId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string state;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string requestCreatorId;
        
        public ArchiveRequest() {
        }
        
        public ArchiveRequest(string requestId, string title, string state, string requestCreatorId) {
            this.requestId = requestId;
            this.title = title;
            this.state = state;
            this.requestCreatorId = requestCreatorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArchiveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArchiveResponse {
        
        public ArchiveResponse() {
        }
    }
}
