//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceModel.Samples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.ServiceModel.Samples.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported channel type..
        /// </summary>
        internal static string ExChannelNotSupported {
            get {
                return ResourceManager.GetString("ExChannelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server connection string could not be found in the configuration file..
        /// </summary>
        internal static string ExConnectionStringNotFound {
            get {
                return ResourceManager.GetString("ExConnectionStringNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Id could not be found in the message header..
        /// </summary>
        internal static string ExContextNotFound {
            get {
                return ResourceManager.GetString("ExContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid context id..
        /// </summary>
        internal static string ExInvalidContextId {
            get {
                return ResourceManager.GetString("ExInvalidContextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory specified by ContextStoreLocation does not seem to be correct..
        /// </summary>
        internal static string ExInvalidContextStorePath {
            get {
                return ResourceManager.GetString("ExInvalidContextStorePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized ContextType is specified in the configuration file..
        /// </summary>
        internal static string ExInvalidContextType {
            get {
                return ResourceManager.GetString("ExInvalidContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This storage manager type does not implement IStorageManager..
        /// </summary>
        internal static string ExInvalidStorageManager {
            get {
                return ResourceManager.GetString("ExInvalidStorageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpCookie context mode is only supported for the HTTP transport..
        /// </summary>
        internal static string ExInvalidTransport {
            get {
                return ResourceManager.GetString("ExInvalidTransport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DurableInstancingAttribute could not be used when InstanceContextMode is set to single..
        /// </summary>
        internal static string ExSingeltonInstancingNotSupported {
            get {
                return ResourceManager.GetString("ExSingeltonInstancingNotSupported", resourceCulture);
            }
        }
    }
}
