//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.ServiceModel.Samples
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Microsoft.ServiceModel.Samples.IErrorCalculator")]
    public interface IErrorCalculator
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/AddResponse")]
        int Add(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Add", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/SubtractResponse")]
        int Subtract(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Subtract", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/SubtractResponse")]
        System.Threading.Tasks.Task<int> SubtractAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/MultiplyResponse")]
        int Multiply(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Multiply", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/DivideResponse")]
        int Divide(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Divide", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/DivideResponse")]
        System.Threading.Tasks.Task<int> DivideAsync(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Factorial", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/FactorialResponse")]
        int Factorial(int n);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IErrorCalculator/Factorial", ReplyAction="http://Microsoft.ServiceModel.Samples/IErrorCalculator/FactorialResponse")]
        System.Threading.Tasks.Task<int> FactorialAsync(int n);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IErrorCalculatorChannel : Microsoft.ServiceModel.Samples.IErrorCalculator, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ErrorCalculatorClient : System.ServiceModel.ClientBase<Microsoft.ServiceModel.Samples.IErrorCalculator>, Microsoft.ServiceModel.Samples.IErrorCalculator
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ErrorCalculatorClient() : 
                base(ErrorCalculatorClient.GetDefaultBinding(), ErrorCalculatorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IErrorCalculator.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ErrorCalculatorClient(EndpointConfiguration endpointConfiguration) : 
                base(ErrorCalculatorClient.GetBindingForEndpoint(endpointConfiguration), ErrorCalculatorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ErrorCalculatorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ErrorCalculatorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ErrorCalculatorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ErrorCalculatorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ErrorCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int Add(int n1, int n2)
        {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int n1, int n2)
        {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public int Subtract(int n1, int n2)
        {
            return base.Channel.Subtract(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> SubtractAsync(int n1, int n2)
        {
            return base.Channel.SubtractAsync(n1, n2);
        }
        
        public int Multiply(int n1, int n2)
        {
            return base.Channel.Multiply(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int n1, int n2)
        {
            return base.Channel.MultiplyAsync(n1, n2);
        }
        
        public int Divide(int n1, int n2)
        {
            return base.Channel.Divide(n1, n2);
        }
        
        public System.Threading.Tasks.Task<int> DivideAsync(int n1, int n2)
        {
            return base.Channel.DivideAsync(n1, n2);
        }
        
        public int Factorial(int n)
        {
            return base.Channel.Factorial(n);
        }
        
        public System.Threading.Tasks.Task<int> FactorialAsync(int n)
        {
            return base.Channel.FactorialAsync(n);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IErrorCalculator))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IErrorCalculator))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/servicemodelsamples/service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ErrorCalculatorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IErrorCalculator);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ErrorCalculatorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IErrorCalculator);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IErrorCalculator,
        }
    }
}
