//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Microsoft.ServiceModel.Samples
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="Microsoft.ServiceModel.Samples.IShoppingCart", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IShoppingCart
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IShoppingCart/AddItem", ReplyAction="http://Microsoft.ServiceModel.Samples/IShoppingCart/AddItemResponse")]
        int AddItem(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IShoppingCart/Clear", ReplyAction="http://Microsoft.ServiceModel.Samples/IShoppingCart/ClearResponse")]
        int Clear();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IShoppingCart/RemoveItem", ReplyAction="http://Microsoft.ServiceModel.Samples/IShoppingCart/RemoveItemResponse")]
        int RemoveItem(string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IShoppingCart/ItemCount", ReplyAction="http://Microsoft.ServiceModel.Samples/IShoppingCart/ItemCountResponse")]
        int ItemCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IShoppingCart/GetCart", ReplyAction="http://Microsoft.ServiceModel.Samples/IShoppingCart/GetCartResponse")]
        string[] GetCart();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IShoppingCartChannel : Microsoft.ServiceModel.Samples.IShoppingCart, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ShoppingCartClient : System.ServiceModel.ClientBase<Microsoft.ServiceModel.Samples.IShoppingCart>, Microsoft.ServiceModel.Samples.IShoppingCart
    {
        
        public ShoppingCartClient()
        {
        }
        
        public ShoppingCartClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ShoppingCartClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShoppingCartClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ShoppingCartClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int AddItem(string item)
        {
            return base.Channel.AddItem(item);
        }
        
        public int Clear()
        {
            return base.Channel.Clear();
        }
        
        public int RemoveItem(string item)
        {
            return base.Channel.RemoveItem(item);
        }
        
        public int ItemCount()
        {
            return base.Channel.ItemCount();
        }
        
        public string[] GetCart()
        {
            return base.Channel.GetCart();
        }
    }
}
